### ISSUE TITLE
Update readme

### ISSUE THREAD

**Issue by Etheryte** [jbreckel/flow-result-checker#1]
Please update the readme with sample usage. Currently trying to use this script results in 

> Skipping /repository/flow/: No such file or directory

and it's unclear whether it's due to a bug or my own misuse.

**Comment by jbreckel** [comment]
could you send me how you use it?
in the meantime I will provide some examples.

**Comment by jbreckel** [comment]
ah, yes when specifying a directory it has to have a leading './' if it should be in your repository.  
will fix that

**Comment by jbreckel** [comment]
could you retry with the latest version and tell me if your problem is solved?

**Comment by Etheryte** [comment]
I still get the same issue when run with the same configuration as shown in the README currently. I'll look deeper into it later.

**Comment by jbreckel** [comment]
could you send me your configuration?

**Comment by jbreckel** [comment]
I updated the API, can you try it again?

**Comment by jbreckel** [comment]
closing for now, feel free to reopen if issue persists
