### ISSUE TITLE
Fails when there are more then 50 errors in node module

### ISSUE THREAD

**Issue by eskimoblood** [jbreckel/flow-result-checker#5]
If there are more then 50 errors are found flow will additionally print
```
'\n... 2 more errors (only 50 out of 52 errors displayed)\nTo see all errors, re-run Flow with --show-all-errors\n'
```
into the stdout. As this is not filtered out the result list has a length on one and the process exits with `1`. Solution: always run flow with `--show-all-errors`

**Comment by jbreckel** [comment]
as this module only parses the flow output the example should be updated
