### ISSUE TITLE
Errors if there is no errors in node_modules

### ISSUE THREAD

**Issue by itsdouges** [jbreckel/flow-result-checker#8]
If you don't have any errors in node_modules you're presented with an error.

![image](https://cloud.githubusercontent.com/assets/6801309/26771621/f60aaaf6-4a02-11e7-877d-c22e07bfd105.png)

![image](https://cloud.githubusercontent.com/assets/6801309/26771627/003f59fe-4a03-11e7-8a93-0eee57ba8ab2.png)

**Comment by jbreckel** [comment]
closed with #7
